name: tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # --- pre‑commit для CI ---
          pip install pre-commit

      # ---------- LINT ----------
      - name: Run pre‑commit (black+flake8)
        run: pre-commit run --all-files
      # ---------------------------

      # UI + API тесты
      - name: Run pytest (UI + API) and collect Allure
        env:
          ATS_USER: ${{ secrets.ATS_USER }}
          ATS_PASS: ${{ secrets.ATS_PASS }}
        run: |
          pytest -q -s \
                 --alluredir=allure-results \
                 tests/ui tests/api

      # Allure artifacts
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
