name: ui-tests               # название job'а (любое)

on: [push, pull_request]     # триггер: каждый push и PR

jobs:
  pytest:
    runs-on: ubuntu-latest   # GitHub выдаст чистый Linux runner
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI tests in headless mode
        env:                     # ← сюда прокинем секреты
          ATS_USER: ${{ secrets.ATS_USER }}
          ATS_PASS: ${{ secrets.ATS_PASS }}
        run: pytest tests/ui -q  # -q = quiet, headless идёт по умолчанию
