name: tests            # название появится в Actions и на бейдже

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - uses: actions/checkout@v3

      # 2. Поднимаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Ставим зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запускаем ВСЕ тесты (UI + API) единой командой
      - name: Run pytest (UI + API) and collect Allure
        env:                      # секреты для UI‑тестов
          ATS_USER: ${{ secrets.ATS_USER }}
          ATS_PASS: ${{ secrets.ATS_PASS }}
        run: |
          pytest -s -q \
                 --alluredir=allure-results \
                 tests/ui tests/api

      # 5. Публикуем отчёт как artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
