name: ui-tests

on: [push, pull_request]

jobs:
  docker-grid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose & run tests
        env:
          ATS_USER: ${{ secrets.ATS_USER }}
          ATS_PASS: ${{ secrets.ATS_PASS }}
        run: |
          docker compose build
          docker compose up --abort-on-container-exit
